### ISSUE TITLE
win10系统运行报错，不知道是什么原因

### ISSUE THREAD

**Issue by ospirekin** [wequgroup/wqy_client#6]
代码如下：
Traceback (most recent call last):
  File "main.py", line 43, in <module>
  File "init.py", line 66, in app
  File "webview\__init__.py", line 129, in start
  File "webview\guilib.py", line 101, in initialize
  File "webview\guilib.py", line 62, in try_import
  File "webview\guilib.py", line 52, in import_winforms
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "webview\platforms\winforms.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 143, in load
  File "clr_loader\types.py", line 64, in __call__
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'

**Comment by monyuan** [comment]
等待新版本发布
